# Generated by Django 3.2.12 on 2022-12-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='to_scrapper_data',
            name='Price',
        ),
        migrations.AddField(
            model_name='to_scrapper_data',
            name='Class_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
