# Generated by Django 3.2.12 on 2022-12-29 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20221229_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapper_data',
            name='user',
        ),
    ]
