# Generated by Django 3.2.12 on 2023-01-01 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_scrapper_data_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='price_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=3000)),
                ('Price', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='product_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='scrapper_data',
        ),
        migrations.AlterField(
            model_name='to_scrapper_data',
            name='Name',
            field=models.CharField(max_length=3000),
        ),
    ]
