# Generated by Django 3.2.12 on 2023-01-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230101_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_scrapper_data',
            name='url',
            field=models.CharField(default=1, max_length=3000),
            preserve_default=False,
        ),
    ]
