# Generated by Django 3.2.12 on 2023-01-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_to_scrapper_data_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_scrapper_data',
            name='website_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
