# Generated by Django 3.2.12 on 2023-01-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_to_scrapper_data_website_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='to_scrapper_data',
            old_name='Class_id',
            new_name='Name_Class_id',
        ),
        migrations.AddField(
            model_name='to_scrapper_data',
            name='Price_Class_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
