# Generated by Django 3.2.12 on 2023-01-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20230101_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_data',
            name='website_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
